In [1]:
import sys
import numpy as np
import tensorflow as tf

In [2]:
from tensorflow.contrib.image.python.ops import image_ops
from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import test_util
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.platform import googletest

In [3]:
_DTYPES = set([dtypes.uint8, dtypes.int32, dtypes.int64, dtypes.float32, dtypes.float64])

In [6]:
with tf.Session(), tf.device('/cpu:0'):
    image = array_ops.zeros([3,3], dtypes.float32)
    print image.eval()
    print image_ops.rotate(image,10).eval()

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [7]:
image_ops.rotate?

In [8]:
print math_ops?

In [ ]:
print math_ops