In [1]:
import tensorflow as tf

In [2]:
tf.one_hot?

In [3]:
sess = tf.Session()
sess.run(tf.one_hot([0, 2, 1, 1], 3))

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.]], dtype=float32)

In [2]:
tf.train.Coordinator?

In [3]:
dir(tf.train.Coordinator)

['__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_filter_exception',
 'clear_stop',
 'join',
 'joined',
 'register_thread',
 'request_stop',
 'should_stop',
 'stop_on_exception',
 'wait_for_stop']

In [2]:
tf.train.start_queue_runners?

In [6]:
tf.train.QueueRunner?

In [7]:
tf.slice?

In [8]:
sess = tf.Session()

In [21]:
sess.run(tf.pad([[1,2,3], [4,5,6],[9,9,9]], [[1,1] ,[1,0]], "CONSTANT"))

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 4, 5, 6],
       [0, 9, 9, 9],
       [0, 0, 0, 0]], dtype=int32)

In [22]:
tf.slice?

In [4]:
tf.contrib.layers.xavier_initializer_conv2d?

In [2]:
tf.group?

In [11]:
tf.InteractiveSession()

In [30]:
input = [[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]],[[5,5,5],[6,6,6]]]
tf.slice(input, [1,0,0],[2,1,1]).eval()

array([[[3]],

       [[5]]], dtype=int32)

In [25]:
input[1:2][0]

[[3, 3, 3], [4, 4, 4]]

In [31]:
tf.nn.softmax_cross_entropy_with_logits?

In [32]:
tf.reduce_mean?

In [33]:
tf.trainable_variables?

In [34]:
tf.add_n?

In [35]:
tf.nn.conv1d?

In [36]:
import nose

In [39]:
nose.run?

In [2]:
tf.train.MomentumOptimizer?

In [3]:
tf.constant?

In [7]:
tf.reduce_mean?

In [6]:
tf.summary?

In [8]:
tf.placeholder?

In [9]:
tf.reset_default_graph?